spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true

  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      default-encoding: UTF-8

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token:
    header: Authorization
    expiration-time: 604800 #60 * 60 * 24 * 7 (7일)
  refresh-token:
    header: Authorization_refresh
    expiration-time: 604800 #60 * 60 * 24 * 7 (7일)
---
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 60MB
---
spring:
  config:
    import: optional:file:/opt/seasonthon/application-secret.yml
