spring:
  profiles:
    active: local
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret
server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local

  security:
    oauth2:
      client:
        registration:
          sign_up:
            redirect-uri: http://localhost:8080/login/oauth2/code/sign_up
          login:
            redirect-uri: http://localhost:8080/login/oauth2/code/login

server:
  port: 8080
  serverAddress: localhost
serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue

  security:
    oauth2:
      client:
        registration:
          sign_up:
            redirect-uri: http://54.206.208.229/login/oauth2/code/sign_up
          login:
            redirect-uri: http://54.206.208.229/login/oauth2/code/login

server:
  port: 8080
  serverAddress: 54.206.208.229

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green

  security:
    oauth2:
      client:
        registration:
          sign_up:
            redirect-uri: http://54.206.208.229/login/oauth2/code/sign_up
          login:
            redirect-uri: http://54.206.208.229/login/oauth2/code/login

server:
  port: 8081
  serverAddress: 54.206.208.229

serverName: green_server

---