spring:
  application:
    name: seasonthon-db
  datasource:
    url: "jdbc:mysql://seasonthon-db.c50wyc4mamqw.ap-southeast-2.rds.amazonaws.com:3306/seasonthon-db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true"
    #jdbc:mysql://seasonthon-db.c50wyc4mamqw.ap-southeast-2.rds.amazonaws.com:3306
    #/seasonthon?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: admin
    password: seasonthon79
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
