name: CICD

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

env:
  JAVA_VERSION: '24'
  APP_IMAGE: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/live_server
  HEALTH_ENDPOINT: env
  BLUE_PORT: '8080'
  GREEN_PORT: '8081'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # application-secret.yml 복원 (Base64/원문 모두 대응)
      - name: Write application-secret.yml (robust)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p src/main/resources
          SECRET="${{ secrets.APPLICATION_SECRET }}"
          if [ -z "$SECRET" ]; then
            echo "::error::APPLICATION_SECRET secret is empty or missing"
            exit 1
          fi
          tmp="$(mktemp)"
          if printf '%s' "$SECRET" | base64 -d > "$tmp" 2>/dev/null; then
            mv "$tmp" src/main/resources/application-secret.yml
            echo "application-secret.yml restored via base64"
          else
            printf '%s' "$SECRET" > src/main/resources/application-secret.yml
            echo "application-secret.yml restored as plain text"
          fi
          test -s src/main/resources/application-secret.yml

      - name: Setup JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Setup Gradle (cache)
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      - name: Docker login (Docker Hub)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.APP_IMAGE }}:${{ github.sha }}
            ${{ env.APP_IMAGE }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Determine current upstream (blue/green) via Nginx (port 80)
        id: pick
        shell: bash
        run: |
          set -e
          # curl 실패를 흡수하고, 타임아웃 단축
          STATUS=$(curl --max-time 3 --connect-timeout 2 -s -o /dev/null -w "%{http_code}" "http://${{ secrets.LIVE_SERVER_IP }}/${{ env.HEALTH_ENDPOINT }}" || echo 000)
          echo "STATUS=$STATUS"
          if [ "$STATUS" = "200" ]; then
            CURRENT_UPSTREAM=$(curl --max-time 3 --connect-timeout 2 -s "http://${{ secrets.LIVE_SERVER_IP }}/${{ env.HEALTH_ENDPOINT }}" || echo green)
          else
            CURRENT_UPSTREAM=green
          fi
          echo "CURRENT_UPSTREAM=$CURRENT_UPSTREAM" >> $GITHUB_ENV
          if [ "$CURRENT_UPSTREAM" = "blue" ]; then
            echo "CURRENT_PORT=${{ env.BLUE_PORT }}"   >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=green"               >> $GITHUB_ENV
            echo "TARGET_PORT=${{ env.GREEN_PORT }}"   >> $GITHUB_ENV
          else
            echo "CURRENT_PORT=${{ env.GREEN_PORT }}"  >> $GITHUB_ENV
            echo "TARGET_UPSTREAM=blue"                >> $GITHUB_ENV
            echo "TARGET_PORT=${{ env.BLUE_PORT }}"    >> $GITHUB_ENV
          fi
          echo "::notice::Will deploy to $TARGET_UPSTREAM on port $TARGET_PORT"

      - name: Deploy target stack via SSH (docker compose up)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIVE_SERVER_IP }}
          username: ec2-user          # Ubuntu AMI면 ubuntu로 바꾸세요
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
            docker pull "${{ env.APP_IMAGE }}:latest"
            docker compose -f "docker-compose-${{ env.TARGET_UPSTREAM }}.yml" up -d
            docker image prune -f

      - name: Health check new color directly (bypass Nginx)
        uses: jtalk/url-health-check-action@v3
        with:
          url: http://${{ secrets.LIVE_SERVER_IP }}:${{ e
